name: Flujo_trabajo

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Permiso mínimo para leer repos
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use GH_PAT
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}